

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require&options=-c%20pool_mode=session
spring.datasource.username=postgres.qmaslbpjdlqhqsofssnq
spring.datasource.password=ptxvL5bcgvo6ze61
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
